### ISSUE TITLE
Add external input status

### ISSUE THREAD

**Issue by RogerSelwyn** [gerard33/sony_bravia_psk#15]
Please can you add the ability to retrieve information from the endpoint sony/avContent with method "getCurrentExternalInputsStatus". This pulls back Information such as:

`            {
                "uri": "extInput:hdmi?port=1",
                "title": "HDMI 1",
                "connection": true,
                "label": "Sky Q",
                "icon": "meta:hdmi",
                "status": "false"
            },
`

I do see on my TV which is a few years old that this will return 500 status code when my HDMI 1 receives input from my Sky box, but until that point it provides information on any label the user may have provided.

If you prefer, I can take a look at creating a PR for it.

**Comment by RogerSelwyn** [comment]
To add some rationale, this is so I can display any label assigned to the input in the front end as shown below. I've also made some code changed in your Bravia component for which I can also prepare a PR.

<img width="502" alt="Screenshot 2020-04-08 at 17 01 36" src="https://user-images.githubusercontent.com/7115783/78806502-a6f25a00-79ba-11ea-9287-5b69f3b8db70.png">

**Comment by gerard33** [comment]
That’s handy data to add indeed. Can you please prepare the PR for the component as well? Than I will have a look at these PRs.

**Comment by RogerSelwyn** [comment]
I'm working on it at the moment, to make sure it is stable. Some things I have noted on my TV.

You don't pull back CEC sources, possibly because they are transient, and you only pull the sources at start-up. So you can find that the source showing in the GUI is one that isn't available on the source list. I don't think this is a major issue.

Also, when I did some testing last night, I start getting 500 internal error on 'getPlayingContentInfo' and 'getCurrentExternalInputsStatus' when the TV has ben changed to my SkyQ CEC input until I put TV and SkyQ box into standby. Doesn't seem to matter what HDMI port the SkyQ box is on and it doesn't do it when I switch to a Apple TV CEC input. So I think there is something on the SkyQ that is causing an error in the Bravia firmware.

Not sure that can be fixed without a firmware update from Sony. I note comments against various other integrations across other platforms over a number of years about 500 errors, but no-one seems to have identified the cause. My testing above looked pretty repeatable.

So in the change I'm creating it will regularly try to get the label list until it has managed to do it the first time after startup, same as you do for the main source list (except that you know you can reliably get it when powered on, whilst I'll check when on standby as well).

If you have any ideas on the 500 issue, that would be good, because it seems to be what causes you to generate 'No info (resumed after pause or app opened)' message.

**Comment by RogerSelwyn** [comment]
Submitted the PR against the HA component - https://github.com/custom-components/media_player.braviatv_psk/pull/27

**Comment by gerard33** [comment]
Closing this as your PR #16 is merged.
