### ISSUE TITLE
Error in log - getVolumeInformation

### ISSUE THREAD

**Issue by RogerSelwyn** [gerard33/sony_bravia_psk#22]
I've had the following errors in my log, I think twice. I suspect it is because of a race condition between checking for whether the TV is switched on or not, and then checking for volume information. I noticed that the TV had just been switched off, when the errors were logged. 

I haven't looked into the code, but I'm happy to try and debug and create a PR. I suspect that it isn't easily replicable, but I'd be pretty sure I can fake the situation so I can trigger the error, so it can be handle better. My suggestion would be to ignore the error (since as the message says, it is an error because the TV is switched off), or at worst put out a single warning message, rather than two errors.

```
2022-03-06 08:01:20 ERROR (SyncWorker_1) [braviapsk.sony_bravia_psk] Invalid response: {'error': [40005, 'Display Is Turned off'], 'id': 1}
request path: sony/audio
request params: {"method": "getVolumeInformation", "params": [], "id": 1, "version": "1.0"}
2022-03-06 08:01:20 ERROR (SyncWorker_1) [braviapsk.sony_bravia_psk] JSON request error:{
"error": [
40005,
"Display Is Turned off"
],
"id": 1
}
```

**Comment by gerard33** [comment]
Fixed in #23.
